version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Build Docker image"
          command: |
            echo ${DOCKER_HUB_PASSWORD} | docker login -u ${DOCKER_HUB_LOGIN} --password-stdin
            docker build -t weezt3ch/cd_app .
            docker push weezt3ch/cd_app

workflows:
  version: 2
  build:
    jobs:
      - build